const countries = {
  China: "CN",
  Japan: "JP",
  Brazil: "BR",
  India: "IN",
  Tanzania: "TZ",
  Andorra: "AD",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahrain: "BH",
  Bahamas: "BS",
  "Brunei Darussalam": "BN",
  Bulgaria: "BG",
  Cameroon: "CM",
  Canada: "CA",
  Chile: "CL",
  Cuba: "CU",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Denmark: "DK",
  "Dominican Republic": "DO",
  Fiji: "FJ",
  France: "FR",
  Germany: "DE",
  Greece: "GR",
  Guam: "GU",
  "United States": "US",
  Indonesia: "ID",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Iran: "IR",
  Liberia: "LR",
  Libya: "LY",
  Lithuania: "LT",
  Mexico: "MX",
  Mozambique: "MZ",
  Netherlands: "NL",
  Norway: "NO",
  Palestine: "PS",
  "Papua New Guinea": "PG",
  Poland: "PL",
  "Russian Federation": "RU",
  "South Africa": "ZA",
  Spain: "ES",
  Sweden: "SE",
  Switzerland: "CH",
  Turkey: "TR",
  "United Kingdom": "GB",
  Yemen: "YE",
  Malaysia: "MY",
  Russia: "RU",
  Kenya: "KE",
  Ethiopia: "ET",
  Somalia: "SO",
  "South Korea": "KR",
  "Republic of the Congo": "CG",
  Maldives: "MV",
  Qatar: "QA",
  Bangladesh: "BD",
  "Sri Lanka": "LK",
  Argentina: "AR",
  Portugal: "PT",
  "Sierra Leone": "SL",
  Bhutan: "BT",
  Turkmenistan: "TM",
  Singapore: "SG",
  Romania: "RO",
  Iceland: "IS",
  Cambodia: "KH",
  Albania: "AL",
  "Hong Kong": "HK",
  Philippines: "PH",
  "Myanmar (Burma)": "MM",
  Honduras: "HN",
  "American Samoa": "AS",
  Nepal: "NP",
  Nauru: "NR",
  Colombia: "CO",
  "United Arab Emirates": "AE",
  Sudan: "SD",
  Morocco: "MA",
  "Burma (Myanmar)": "MM",
  Nicaragua: "NI",
  Algeria: "DZ",
  Kazakhstan: "KZ",
  Zambia: "ZM",
  Mauritania: "MR",
  Peru: "PE",
  "New Zealand": "NZ",
  Zimbabwe: "ZW",
  "Central African Republic": "CF",
  Pakistan: "PK",
  Iraq: "IQ",
  Niue: "NU",
  Finland: "FI",
  Afghanistan: "AF",
  Haiti: "HT",
  "Costa Rica": "CR",
  Guinea: "GN",
  Angola: "AO",
  "New Caledonia": "NC",
  Laos: "LA",
  Vietnam: "VN",
  "Democratic Republic of the Congo": "CG",
  Thailand: "TH",
  Gabon: "GA",
  Guyana: "GY",
  Korea: "KR",
  Rwanda: "RW",
  Ukraine: "UA",
  "Federated States of Micronesia": "FM",
  Slovakia: "SK",
  Uganda: "UG",
  Uzbekistan: "UZ",
  Mali: "ML",
  "Ivory Coast": "CI",
  Jamaica: "JM",
  Kiribati: "KI",
  "Solomon Islands": "SB",
  Greenland: "GL",
  Georgia: "GE",
  "Marshall Islands": "MH",
  Kuwait: "KW",
  "Saudi Arabia": "SA",
  Djibouti: "DJ",
  Ecuador: "EC",
  Malawi: "MW",
  Benin: "BJ",
  Mongolia: "MN",
  Belgium: "BE",
  Grenada: "GD",
  Senegal: "SN",
  Panama: "PA",
  Guatemala: "GT",
  Oman: "OM",
  Nigeria: "NG",
  Belarus: "BY",
  "French Polynesia": "PF",
  Taiwan: "TW",
  Botswana: "BW",
  Namibia: "NA",
  Madagascar: "MG",
  Saudi: "SA",
  Tajikistan: "TJ",
  Mayotte: "YT",
  Uruguay: "UY",
  Tunisia: "TN",
  Egypt: "EG",
  "Cayman Islands": "KY",
  "South Sudan": "SS",
  Venezuela: "VE",
  Slovenia: "SI",
  Lebanon: "LB",
  "Island, Samoa": "WS",
  "CÃ´te dIvoire": "CI",
  Suriname: "SR",
  Ghana: "GH",
  Jordan: "JO",
  Barbados: "BB",
  Monaco: "MC",
  Hungary: "HU",
  Belize: "BZ",
  "Turks and Caicos Islands": "TC",
  Chad: "TD",
  "Saint Kitts and Nevis": "KN",
  "Viet Nam": "VN",
  Syria: "SY",
  Myanmar: "MM",
  "CuraÃ§ao": "CW",
  "French Guiana": "GF",
  Lesotho: "LS",
  Niger: "NE",
  Estonia: "EE",
  "Syrian Arab Republic": "SY",
  Croatia: "HR",
  "Lao Peoples Democratic Republic": "LA",
  Dominica: "DM",
  Togo: "TG",
  Bolivia: "BO",
  Paraguay: "PY",
  "Cook Islands": "CK",
  Comoros: "KM",
  "Saint Vincent and the Grenadines": "VC",
  Malta: "MT",
  Seychelles: "SC",
  Latvia: "LV",
  "Timor-Leste": "TL",
  Gambia: "GM",
  Burundi: "BI",
  Serbia: "RS",
  Moldova: "MD",
  "Norfolk Island": "NF",
  Micronesia: "FM",
  Congo: "CG",
  "Trinidad and Tobago": "TT",
  "Virgin Islands": "VG",
  Vanuatu: "VU",
  "Burkina Faso": "BF",
  Guadeloupe: "GP",
  "Puerto Rico": "PR",
  "Cape Verde": "CV",
  Tonga: "TO",
  Bermuda: "BM",
  Bonaire: "BQ",
  Armenia: "AM",
  "Bosnia and Herzegovina": "BA",
  "CÃ´te d Ivoire": "CI",
  "Falkland Islands (Islas Malvinas)": "FK",
  "Antigua and Barbuda": "AG",
  Martinique: "MQ",
  Samoa: "WS",
  "United States Minor Outlying Islands": "UM",
  Macao: "MO",
  Eritrea: "ER",
  Aruba: "AW",
  CotedIvoire: "CI",
  Macedonia: "MK",
  "Equatorial Guinea": "GQ",
  "Falkland Islands (Malvinas)": "FK",
  Czechia: "CZ",
  Luxembourg: "LU",
  "Cocos (Keeling) Islands": "CC",
  "The Bahamas": "BS",
  TimorLeste: "TL",
  Mauritius: "MU",
  Swaziland: "SZ",
  Anguilla: "AI",
  Kyrgyzstan: "KG",
  Tuvalu: "TV",
  "Guinea-Bissau": "GW",
  England: "UK",
  Gibraltar: "GI",
  "North Korea": "KP",
  "RÃ©union": "RE",
  "Northern Mariana Islands": "MP",
  Palau: "PW",
  "Sint Maarten (Dutch part)": "SX",
  "El Salvador": "SV",
  "Saint Lucia": "LC",
  Montenegro: "ME",
  "Western Sahara": "EH",
  "Sao Tome and Principe": "ST",
  Antarctica: "AQ",
  "Christmas Island": "CX",
};

export default countries;